# GENERATED by scripts/sync-core.js -- edit the root-level copy of this file instead, then run `npm run sync`.
#!/usr/bin/env python3
"""Shared Kia/Hyundai client used by the MagicMirror bridge and (vendored) by
the Home Assistant integration.

Wraps hyundai_kia_connect_api.VehicleManager with:
  * region / brand name -> int maps
  * token.json load + save (preserving the original enrolment timestamp)
  * connect()  -> an authenticated VehicleManager (raises OtpRequired if not enrolled)
  * fetch(job) -> {"ok": True, "vehicles": [...], "meta": {...}}  (read path)
  * run_command(job) -> {"ok": True, "command": "...", ...}       (control path)

The control commands are described by core/commands.json so the HA integration,
the Lovelace card and this module all agree on names and arguments.
"""

import datetime
import enum
import hashlib
import json
import logging
import math
import os
import stat
import threading
import time

_LOGGER = logging.getLogger(__name__)

_HERE = os.path.dirname(os.path.abspath(__file__))
# Pre-v2.63 default: a single shared token.json for every account. Two
# MagicMirror module instances (or module blocks) configured with DIFFERENT
# Kia accounts both fell back to this same file -- each one's token refresh
# silently overwrote the other's, so whichever account polled last would
# leave the OTHER account authenticating with the wrong (or freshly revoked)
# token on its next cycle. See account_token_file() / DEFAULT_TOKEN_FILE's
# remaining role as a one-time migration source, below.
DEFAULT_TOKEN_FILE = os.path.join(_HERE, "token.json")


def _account_hash(region, brand, username) -> str:
    """sha256(REGION|BRAND|username), truncated -- same non-cryptographic
    identity-hashing idea node_helper.js's _idHash() uses for cache files
    (there's no Node/Python code-sharing path for this one, so it's a
    separate implementation of the same idea). Token identity is scoped to
    the ACCOUNT (region+brand+username), not a specific vehicle -- one Kia
    login's token is shared across every vehicle on that account."""
    raw = f"{str(region).upper()}|{str(brand).upper()}|{str(username).strip().lower()}"
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()[:16]


def account_token_file(job) -> str:
    """The token file THIS job's account owns -- distinct per (region, brand,
    username), so two differently-configured accounts never share one file."""
    h = _account_hash(
        job.get("region", "USA"), job.get("brand", "KIA"), job.get("username", "")
    )
    return os.path.join(_HERE, f"token-{h}.json")


def _auth_state_file(job) -> str:
    """Per-account, alongside the token file (same _HERE + account-hash
    convention account_token_file() already uses)."""
    h = _account_hash(
        job.get("region", "USA"), job.get("brand", "KIA"), job.get("username", "")
    )
    return os.path.join(_HERE, f"authstate-{h}.json")


# A live token that fails to re-auth means Kia is rejecting THIS account's
# login, not "the network blipped" -- retrying it on the normal poll/retry
# schedule just repeats the same failing login call over and over, which is
# exactly the kind of pattern that gets an account rate-limited or locked
# out (a real incident: repeated failed re-logins during a setup retry loop
# preceded a user's Kia Connect account getting locked). AUTH_FAILURE_
# THRESHOLD consecutive failures within AUTH_FAILURE_WINDOW_SEC trips a
# cooldown -- connect() then refuses to even attempt check_and_refresh_
# token() again until it expires, so a broken login stops generating any
# further traffic to Kia at all instead of merely slowing down.
AUTH_FAILURE_THRESHOLD = 3
AUTH_FAILURE_WINDOW_SEC = 15 * 60
AUTH_COOLDOWN_BASE_MIN = 30
AUTH_COOLDOWN_MAX_MIN = 240  # 4h ceiling -- still eventually retries on its own


def _load_auth_state(path) -> dict:
    try:
        with open(path, encoding="utf-8") as fh:
            state = json.load(fh)
        return state if isinstance(state, dict) else {}
    except Exception:
        return {}


def _save_auth_state(path, state) -> None:
    try:
        with open(path, "w", encoding="utf-8") as fh:
            json.dump(state, fh)
    except OSError:
        pass


def _cooldown_remaining_sec(state, now=None) -> float:
    """0 if not currently in a cooldown window, else seconds left in it."""
    now = time.time() if now is None else now
    until = state.get("cooldownUntil")
    if until is None:
        return 0.0
    return max(0.0, until - now)


def _record_auth_failure(state, now=None) -> dict:
    """New state after one more consecutive auth failure. Escalates into
    (and lengthens) a cooldown once AUTH_FAILURE_THRESHOLD is reached
    within the window; resets the count outside the window (an isolated
    failure weeks apart from the next isn't "repeated")."""
    now = time.time() if now is None else now
    last = state.get("lastFailureAt")
    count = state.get("consecutiveFailures", 0)
    if last is None or (now - last) > AUTH_FAILURE_WINDOW_SEC:
        count = 0
    count += 1
    new_state = dict(state)
    new_state["consecutiveFailures"] = count
    new_state["lastFailureAt"] = now
    if count >= AUTH_FAILURE_THRESHOLD:
        prior = state.get("cooldownsTriggered", 0)
        minutes = min(AUTH_COOLDOWN_BASE_MIN * (2 ** prior), AUTH_COOLDOWN_MAX_MIN)
        new_state["cooldownUntil"] = now + minutes * 60
        new_state["cooldownsTriggered"] = prior + 1
        new_state["consecutiveFailures"] = 0  # this window's count is spent
    return new_state


def _migrate_legacy_token(token_file, account_hash) -> None:
    """One-time migration off the old shared token.json, mirroring
    node_helper.js's migrateLegacyCache(): adopt (rename) the legacy file
    ONLY if it's never been tagged with an account's identity (a fresh
    upgrade from a pre-v2.63, single-account-only install) -- a legacy file
    already tagged for a DIFFERENT account must never be adopted here, or a
    second account set up after the first already migrated would silently
    steal the first account's still-in-use token."""
    if os.path.exists(token_file) or not os.path.exists(DEFAULT_TOKEN_FILE):
        return
    try:
        with open(DEFAULT_TOKEN_FILE, encoding="utf-8") as fh:
            raw = json.load(fh)
    except Exception:
        return  # unreadable/corrupt -- not a safe migration candidate
    if not (isinstance(raw, dict) and not raw.get("_kiaAccessAccountHash")):
        return  # already tagged (for this or another account) -- never adopt
    try:
        os.rename(DEFAULT_TOKEN_FILE, token_file)
    except OSError:
        pass
# repo layout: <root>/core/commands.json ; HA vendored copy: alongside this file
COMMANDS_FILE = next(
    (p for p in (
        os.path.join(_HERE, "core", "commands.json"),
        os.path.join(_HERE, "commands.json"),
    ) if os.path.exists(p)),
    os.path.join(_HERE, "core", "commands.json"),
)

ENROLL_HINT = (
    "OTP enrollment required. Run once on the mirror: "
    "echo '<same JSON>' | venv/bin/python3 enroll.py  (see README)"
)

REGION_INT = {
    "EU": 1, "EUROPE": 1,
    "CA": 2, "CANADA": 2,
    "US": 3, "USA": 3,
    "CN": 4, "CHINA": 4,
    "AU": 5, "AUSTRALIA": 5,
    "IN": 7, "INDIA": 7,
    "NZ": 8,
    "BR": 9, "BRAZIL": 9,
}
BRAND_INT = {"KIA": 1, "HYUNDAI": 2, "GENESIS": 3}


class OtpRequired(Exception):
    """The saved token is missing/expired and interactive OTP enrollment is needed."""


class ClientError(Exception):
    """Any other failure worth reporting to the caller verbatim."""


class CommandUnconfirmed(ClientError):
    """A control command's HTTP request timed out (or the car itself never
    answered) -- Kia's own protocol gives no ID-less way to ask afterward
    "did anything get queued for this vehicle?", so whether the command
    actually landed is genuinely unknown, not "failed". A subclass of
    ClientError so existing `except ClientError` callers keep working
    unchanged; callers that care about the distinction can catch this
    specifically to avoid treating a blind retry as safe."""


# ---------------------------------------------------------------------------
# JSON helpers (shared with the bridge's vehicle dump)
# ---------------------------------------------------------------------------
def jsonable(value):
    if isinstance(value, (datetime.datetime, datetime.date, datetime.time)):
        return value.isoformat()
    if isinstance(value, datetime.timezone):
        return str(value)
    if isinstance(value, (list, tuple)):
        return [jsonable(v) for v in value]
    if isinstance(value, dict):
        return {str(k): jsonable(v) for k, v in value.items()}
    if isinstance(value, (str, int, float, bool)) or value is None:
        return value
    # hyundai_kia_connect_api sets several Vehicle fields (engine_type, most
    # notably) to a plain `Enum` member, not the `.value` string the field's
    # own type annotation claims -- Python's plain Enum.__str__ renders as
    # "ENGINE_TYPES.EV", not "EV", so falling through to the generic
    # str(value) below would silently serialize engine_type as the literal,
    # useless string "ENGINE_TYPES.EV" instead of "EV". Every consumer
    # matching on this field (e.g. a car-diagram powertrain picker mapping
    # "ICE"/"PHEV"/"HEV"/"EV" to gas/hybrid/ev) would then just never match
    # anything and silently fall back to its default.
    if isinstance(value, enum.Enum):
        return jsonable(value.value)
    return str(value)


def _flatten_scalar_seq(val):
    if isinstance(val, (list, tuple)):
        parts = [str(x) for x in val if x is not None and x != ""]
        return ", ".join(parts) if parts else None
    return val


def dump_vehicle(vehicle):
    """Every readable public attribute + property off the Vehicle object."""
    out = {}
    for attr in dir(vehicle):
        if attr.startswith("_"):
            continue
        try:
            val = getattr(vehicle, attr)
        except Exception:
            continue
        if callable(val):
            continue
        if isinstance(val, (list, tuple)) and all(
            not isinstance(x, (list, tuple, dict)) for x in val
        ):
            val = _flatten_scalar_seq(val)
        try:
            out[attr] = jsonable(val)
        except Exception:
            out[attr] = repr(val)
    try:
        out["data"] = jsonable(getattr(vehicle, "data", {}) or {})
    except Exception:
        pass

    # The library pairs each temperature / distance with the account's local
    # unit (°F + miles for USA & Canada) but stores the raw value — while every
    # downstream formatter (state.js, visuals.js, the HA sensors' device classes)
    # assumes °C / km. Normalise here, the one place both surfaces share.
    _F = ("F", "°F", "FAHRENHEIT")
    _MI = ("MI", "MILES", "MILE")
    for base in ("air_temperature", "outside_temperature"):
        unit = getattr(vehicle, "_" + base + "_unit", None)
        val = out.get(base)
        if isinstance(val, (int, float)) and not isinstance(val, bool) and \
                str(unit).strip().upper() in _F:
            out[base] = round((val - 32) * 5.0 / 9.0, 1)
    for base in (
        "odometer", "ev_driving_range", "total_driving_range",
        "fuel_driving_range", "next_service_distance", "last_service_distance",
    ):
        unit = getattr(vehicle, "_" + base + "_unit", None)
        val = out.get(base)
        if isinstance(val, (int, float)) and not isinstance(val, bool) and \
                str(unit).strip().upper() in _MI:
            out[base] = round(val * 1.609344, 1)
            if base + "_unit" in out:
                out[base + "_unit"] = "km"

    # Domain-range guard: NaN/Infinity/coordinate-range hardening already
    # exists throughout the HA coordinator (_haversine_km, _zone_radius_m,
    # _valid_ll) for GPS specifically -- this is the equivalent for the
    # vehicle's own percentage/range readings, at the one place both MM and
    # HA share (dump_vehicle() is this shared function's whole job). A
    # structurally-valid-looking but semantically impossible reading (Kia's
    # API has been seen, rarely, to report a battery percentage outside
    # 0-100 mid-sync) becomes None ("no data this poll") rather than a fake
    # but plausible-looking number -- clamping to a boundary instead could
    # read as a genuine "fully charged"/"empty" and trigger a false alert,
    # where None just means the next poll's real value is awaited, the same
    # as any other momentarily-missing field.
    for key in ("ev_battery_percentage", "ev_battery_soh_percentage",
                "car_battery_percentage", "fuel_level"):
        val = out.get(key)
        if isinstance(val, (int, float)) and not isinstance(val, bool):
            if not math.isfinite(val) or val < 0 or val > 100:
                out[key] = None
    for key in ("odometer", "ev_driving_range", "total_driving_range",
                "fuel_driving_range"):
        val = out.get(key)
        if isinstance(val, (int, float)) and not isinstance(val, bool):
            if not math.isfinite(val) or val < 0:
                out[key] = None

    return out


def load_commands():
    with open(COMMANDS_FILE, encoding="utf-8") as fh:
        return json.load(fh).get("commands", [])


# ---------------------------------------------------------------------------
# token.json
# ---------------------------------------------------------------------------
def _load_token(token_file, Token, token_dict=None):
    """Prefer an inline token dict (HA config entry); fall back to token.json."""
    raw = None
    if isinstance(token_dict, dict) and token_dict:
        raw = token_dict
    elif token_file and os.path.exists(token_file):
        try:
            with open(token_file, encoding="utf-8") as fh:
                raw = json.load(fh)
        except Exception:
            raw = None
    if not raw:
        return None, None
    try:
        return Token.from_dict(raw), raw.get("enrolled_at")
    except Exception:
        return None, None


def token_dict(vm, enrolled_at=None):
    """Serialise vm.token for storage, keeping the original enrolment time."""
    if vm.token is None:
        return None
    tok = vm.token.to_dict()
    tok["enrolled_at"] = enrolled_at or datetime.datetime.now(
        datetime.timezone.utc
    ).isoformat()
    return tok


def _save_token(token_file, vm, enrolled_at, account_hash=None):
    if vm.token is None:
        return
    # Write-then-rename (same pattern node_helper.js's persist() uses for the
    # vehicle cache): a catastrophic interruption -- power loss, the process
    # killed -- mid-write used to be able to leave token_file itself
    # truncated/corrupt, since the write truncated it in place. Writing to a
    # sibling .tmp file first and only replacing the real file with an
    # atomic os.replace() means the real file is always either the old
    # complete token or the new complete one, never a partial write.
    tmp = token_file + ".tmp"
    try:
        tok = vm.token.to_dict()
        tok["enrolled_at"] = enrolled_at or datetime.datetime.now(
            datetime.timezone.utc
        ).isoformat()
        # Identity tag -- see _migrate_legacy_token()'s comment for why this
        # exists: it's what stops a SECOND account's setup from ever being
        # able to adopt an already-tagged file belonging to a DIFFERENT
        # account during the legacy-token.json migration.
        if account_hash:
            tok["_kiaAccessAccountHash"] = account_hash
        # Create already owner-only rather than open()-then-chmod(): the
        # latter briefly leaves the refresh token world/group-readable
        # (whatever the umask allows) between the write and the chmod call --
        # a real window on every token rotation, not just at enrollment.
        fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            json.dump(tok, fh, indent=2, default=str)
        os.chmod(tmp, stat.S_IRUSR | stat.S_IWUSR)
        os.replace(tmp, token_file)  # atomic on both POSIX and Windows
    except Exception as exc:  # noqa: BLE001
        # non-fatal (the caller already has a good fetch to hand back this
        # cycle) but must NOT be silent -- a failed rotation here means the
        # next run authenticates with a stale token and fails for a reason
        # that's invisible without this line.
        _LOGGER.warning("Kia Access: could not persist rotated token to %s: %s",
                         token_file, exc)
        try:
            os.unlink(tmp)
        except OSError:
            pass


# ---------------------------------------------------------------------------
# connect
# ---------------------------------------------------------------------------
def _region_brand(job):
    region = REGION_INT.get(str(job.get("region", "USA")).upper())
    brand = BRAND_INT.get(str(job.get("brand", "KIA")).upper())
    if region is None:
        raise ClientError(f"unknown region {job.get('region')!r}")
    if brand is None:
        raise ClientError(f"unknown brand {job.get('brand')!r}")
    return region, brand


def make_manager(job, saved_token=None):
    """Build a VehicleManager without logging in (used by the HA OTP flow)."""
    try:
        from hyundai_kia_connect_api import VehicleManager
    except Exception as exc:
        raise ClientError(
            "hyundai_kia_connect_api is not installed."
        ) from exc
    region, brand = _region_brand(job)
    geocode = bool(job.get("geocode", False))
    return VehicleManager(
        region=region,
        brand=brand,
        username=job["username"],
        password=job["password"],
        pin=str(job.get("pin", "")),
        token=saved_token,
        geocode_api_enable=geocode,
        geocode_api_use_email=geocode,
    )


def connect(job, token_file=None):
    """Return (vm, enrolled_at). Raises OtpRequired / ClientError."""
    account_hash = _account_hash(
        job.get("region", "USA"), job.get("brand", "KIA"), job.get("username", "")
    )
    token_file = token_file or job.get("tokenFile") or account_token_file(job)
    _migrate_legacy_token(token_file, account_hash)
    try:
        from hyundai_kia_connect_api import VehicleManager
        from hyundai_kia_connect_api.Token import Token
    except Exception as exc:
        raise ClientError(
            "hyundai_kia_connect_api is not installed. Run: "
            "pip3 install hyundai_kia_connect_api"
        ) from exc

    try:
        from hyundai_kia_connect_api.exceptions import AuthenticationOTPRequired
    except Exception:
        class AuthenticationOTPRequired(Exception):
            pass

    region, brand = _region_brand(job)

    saved_token, enrolled_at = _load_token(token_file, Token, job.get("token"))
    geocode = bool(job.get("geocode", False))
    vm = VehicleManager(
        region=region,
        brand=brand,
        username=job["username"],
        password=job["password"],
        pin=str(job.get("pin", "")),
        token=saved_token,
        geocode_api_enable=geocode,
        geocode_api_use_email=geocode,
    )

    auth_state_file = _auth_state_file(job)
    auth_state = _load_auth_state(auth_state_file)
    remaining = _cooldown_remaining_sec(auth_state)
    if remaining > 0:
        mins = int(remaining // 60) + 1
        # Refuses even the attempt -- no call to Kia's servers happens at
        # all while cooling down, not just a slower retry.
        raise ClientError(
            f"cooling down after {AUTH_FAILURE_THRESHOLD} repeated "
            f"authentication failures -- not contacting Kia's servers again "
            f"for ~{mins} more min. This is deliberate: retrying a broken "
            "login on the normal schedule is what can get an account "
            "rate-limited or locked out in the first place."
        )

    try:
        vm.check_and_refresh_token()
    except AuthenticationOTPRequired as exc:
        raise OtpRequired(ENROLL_HINT) from exc
    except Exception as exc:
        new_state = _record_auth_failure(auth_state)
        _save_auth_state(auth_state_file, new_state)
        if new_state.get("cooldownUntil"):
            mins = int((new_state["cooldownUntil"] - time.time()) // 60) + 1
            raise ClientError(
                f"authentication failed {AUTH_FAILURE_THRESHOLD} times in a "
                f"row ({exc}) -- cooling down for ~{mins} min instead of "
                "continuing to retry, to avoid making a likely account "
                "lockout worse. This will clear and retry normally on its own."
            ) from exc
        raise

    if auth_state:  # only touch disk when there was something to clear
        _save_auth_state(auth_state_file, {})

    # Persist the rotated token to token.json only for the file-based caller
    # (the MagicMirror bridge, which never puts a "token" key in the job). When
    # the caller manages the token itself (Home Assistant passes it in the job
    # and reads it back from fetch()'s meta["token"]), don't write anything into
    # the HACS-managed integration folder.
    if "token" not in job:
        _save_token(token_file, vm, enrolled_at, account_hash)
    return vm, enrolled_at


def _vehicle_key(vehicle) -> str:
    """The stable per-vehicle identifier used for VIN-based selection/config:
    the real VIN when the connected region's API implementation actually
    reports one, falling back to the vehicle's own account-issued `id`
    (vehicleIdentifier) when it doesn't.

    As of the installed hyundai_kia_connect_api version (checked against its
    latest upstream source too -- this isn't fixed even on main),
    KiaUvoApiUSA.get_vehicles() -- Kia brand, USA region -- never sets
    Vehicle.VIN at all; every other region/brand implementation
    (KiaUvoApiCA/CN/IN, GspaApiEU, HyundaiBlueLinkApiUSA/BR, ApiImplType1)
    does. A single-vehicle account never notices (nothing filters on VIN
    when it's blank), but VIN-based vehicle SELECTION -- the "choose a
    vehicle" step, the Configure VIN picker, kia_client.fetch()'s own VIN
    matching -- silently matched nothing for every Kia USA multi-vehicle
    account before this fallback existed. `.id` is just as stable/unique
    per vehicle for this purpose (picking ONE vehicle out of an account),
    even though it isn't literally the car's VIN."""
    vin = str(getattr(vehicle, "VIN", "") or "").strip().upper()
    if vin:
        return vin
    return str(getattr(vehicle, "id", "") or "").strip().upper()


def _vehicle_key_dict(v: dict) -> str:
    """Same as _vehicle_key() but for an already-dumped vehicle dict (e.g.
    dump_vehicle()'s output, or fetch()'s "vehicles" list) rather than a
    live Vehicle object."""
    vin = str(v.get("VIN") or "").strip().upper()
    if vin:
        return vin
    return str(v.get("id") or "").strip().upper()


def _select_vehicles(vm, vin):
    vin = str(vin or "").strip().upper()
    out = []
    for vehicle in vm.vehicles.values():
        if vin and _vehicle_key(vehicle) != vin:
            continue
        out.append(vehicle)
    return out


def _no_match_error(vm, vin) -> "ClientError":
    """A "no matching vehicles" ClientError that actually says something --
    plain "no matching vehicles on the account" told a real multi-vehicle
    account user nothing (not even whether it was a configured VIN
    mismatch or the account genuinely returning zero vehicles that poll),
    which is exactly why there was nothing useful to find in the logs
    when this fired."""
    vin = str(vin or "").strip().upper()
    seen = sorted({_vehicle_key(v) for v in vm.vehicles.values()} - {""})
    if not vin:
        return ClientError(
            "no matching vehicles on the account (the account API returned "
            "0 vehicles this poll -- if this persists, check the Kia/Hyundai "
            "app itself shows the car, and that the account has cloud/remote "
            "access, not just Bluetooth-only connectivity)"
        )
    if not seen:
        return ClientError(
            f"no vehicle on the account matches the configured VIN {vin!r} -- "
            "the account API returned 0 vehicles this poll (a transient gap, "
            "or the account temporarily has no cloud-connected vehicle)"
        )
    return ClientError(
        f"no vehicle on the account matches the configured VIN {vin!r} -- "
        f"the account currently has: {', '.join(seen)}. If the car's real VIN "
        "isn't in that list, remove and re-add the integration to pick it up "
        "fresh; if it IS in that list, the config's stored VIN doesn't match "
        "it (re-run Configure and re-select the vehicle)."
    )


# ---------------------------------------------------------------------------
# read path
# ---------------------------------------------------------------------------
def fetch(job, token_file=None):
    vm, enrolled_at = connect(job, token_file)

    meta_note = None
    _raw_to = job.get("forceRefreshTimeout", 45)
    timeout = float(_raw_to) if _raw_to is not None else 45.0
    # refresh:false (MM) or a zero/negative wake-up timeout (HA "Live wake-up
    # timeout = 0") both mean: don't wake the car, just read Kia's server cache.
    if job.get("refresh", True) and timeout > 0:
        err = {}

        def _do_refresh():
            try:
                vm.force_refresh_all_vehicles_states()
            except Exception as exc:
                err["e"] = exc

        th = threading.Thread(target=_do_refresh, daemon=True)
        th.start()
        th.join(timeout)
        if th.is_alive():
            # The background thread is still inside force_refresh_all_vehicles_
            # states(), which mutates `vm`'s vehicle objects in place -- reading
            # them now (update_all_vehicles_with_cached_state() + dump_vehicle()
            # below) would race an unsynchronized write from another thread on
            # the very same objects, up to and including a mid-iteration
            # RuntimeError. Fail this fetch cleanly instead: the caller
            # (coordinator.py / node_helper.js) already has a "keep serving the
            # last known good state" fallback for exactly this case, which is a
            # strictly better outcome than a torn/corrupted live read. The
            # orphaned thread finishes on its own (it's daemonized) against a
            # `vm` nothing else will ever touch again.
            raise ClientError(
                f"live wake-up timed out after {int(timeout)}s — will retry next cycle"
            )
        elif "e" in err:
            meta_note = f"live wake-up failed: {err['e']}"
    vm.update_all_vehicles_with_cached_state()

    selected = _select_vehicles(vm, job.get("vin", ""))
    if not selected:
        raise _no_match_error(vm, job.get("vin", ""))
    if not job.get("vin") and not job.get("allVehicles") and len(selected) > 1:
        # Reads used to silently fall back to "vehicle 1" here, same as the
        # control path used to before it was locked down (see run_command()).
        # Without an explicit VIN, which physical car that is can change
        # between polls (the account API's own vehicle order isn't
        # guaranteed stable) -- silently mixing two cars' data into one set
        # of entities/history/sessions/trips/alerts is worse than a clear,
        # one-time setup error asking for a VIN. Fail loudly instead of
        # guessing, for both callers of this shared function (MM and HA).
        #
        # allVehicles is the one deliberate opt-in bypass: MM's rotate-
        # within-one-module feature WANTS every vehicle back in one call, and
        # keeps them apart itself (one cache/history/session id per VIN --
        # see node_helper.js's handleFetch()), so there's no ambiguity here,
        # just an explicit "give me all of them."
        raise ClientError(
            f"{len(selected)} vehicles on this account — set a VIN in the "
            "config to pick one (reads need an explicit target, same as "
            "control commands)"
        )
    vehicles = [dump_vehicle(v) for v in selected]

    meta = {}
    if meta_note:
        meta["note"] = meta_note
    if enrolled_at:
        meta["tokenEnrolledAt"] = enrolled_at
    # hand back the (possibly rotated) token so an in-process caller (HA) can
    # persist it; the MM bridge ignores this and relies on token.json
    tok = token_dict(vm, enrolled_at)
    if tok:
        meta["token"] = tok
    first = vehicles[0]
    if not first.get("last_updated_at") and not (first.get("data") or {}):
        meta["warning"] = (
            "Kia returned an empty state for this vehicle. Open the Kia app "
            "once to force a sync, or try again shortly."
        )
    return {"ok": True, "vehicles": vehicles, "meta": meta}


# ---------------------------------------------------------------------------
# control path
# ---------------------------------------------------------------------------
def run_command(job, token_file=None):
    name = job.get("command")
    spec = next((c for c in load_commands() if c["key"] == name), None)
    if spec is None:
        raise ClientError(f"unknown command {name!r}")

    vm, _ = connect(job, token_file)
    vm.update_all_vehicles_with_cached_state()
    selected = _select_vehicles(vm, job.get("vin", ""))
    if not selected:
        raise _no_match_error(vm, job.get("vin", ""))
    if not job.get("vin") and len(selected) > 1:
        # Reads can reasonably default to "vehicle 1" (see fetch()) -- a
        # remote command cannot. Without an explicit VIN, `selected[0]` is
        # whichever vehicle the account API happened to list first THIS
        # call, which is not guaranteed stable; sending lock/unlock/climate/
        # charge to an arbitrary, possibly-wrong physical vehicle is a real
        # safety issue, not just a data-quality one.
        raise ClientError(
            f"{len(selected)} vehicles on this account — set a VIN before "
            f"running '{name}' (control commands need an explicit target)"
        )
    vehicle_id = selected[0].id

    method = getattr(vm, spec["method"], None)
    if method is None:
        raise ClientError(
            f"hyundai_kia_connect_api has no '{spec['method']}' — library too old?"
        )

    opts = job.get("options") or {}
    opt_specs = spec.get("options") or {}
    call = spec.get("call", "bare")
    # options like start_climate's set_temp carry a region-specific "metric"
    # variant of default/min/max (see core/commands.json's $comment) --
    # everything else about the catalogue is region-agnostic, so only the
    # DEFAULT substitution needs this; an explicitly-passed value (e.g. from
    # the HA climate entity, which already converts correctly) is trusted
    # as-is and never reinterpreted here.
    #
    # USA only, NOT Canada: hyundai_kia_connect_api's KiaUvoApiCA.start_climate
    # takes set_temp in CELSIUS (self.temperature_range_c_new, 14.0-31.5 in
    # 0.5 steps -- KiaUvoApiCA.py) and does a hard `.index(options.set_temp)`
    # lookup into that tuple; only KiaUvoApiUSA actually wants Fahrenheit.
    # Treating CA as a Fahrenheit region (as this project did through v2.87.x)
    # sends a 62-82 value that is never in that tuple, so start_climate
    # raises an unhandled ValueError on every single call for a Canadian
    # account -- confirmed against the installed library source, not assumed.
    fahrenheit = str(job.get("region", "USA")).upper() == "USA"

    def _with_default(key):
        spec_for_key = opt_specs.get(key) or {}
        metric = spec_for_key.get("metric")
        if key in opts:
            val = opts[key]
            # Defense in depth for a region-ambiguous option (currently just
            # set_temp): the HA service schema's min/max is a UNION of both
            # regions' ranges (it can't be region-scoped, see core/commands.
            # json's $comment), so schema validation alone lets a Fahrenheit
            # value through to a metric vehicle and vice versa. The native
            # climate entity's build_climate_options() always sends an
            # already-correctly-converted value for THIS vehicle's region,
            # so it will never trip this; a raw/automation service call
            # sending the wrong region's value now gets a clear error
            # instead of silently reaching the vehicle wrong.
            if metric and isinstance(val, (int, float)) and not isinstance(val, bool):
                bounds = spec_for_key if fahrenheit else metric
                lo, hi = bounds.get("min"), bounds.get("max")
                if (lo is not None and val < lo) or (hi is not None and val > hi):
                    unit = bounds.get("unit") or ""
                    raise ClientError(
                        f"{key}={val!r} is outside the valid range for this "
                        f"vehicle's region ({lo}-{hi}{' ' + unit if unit else ''})"
                        " -- omit it to use the region's default"
                    )
            return val
        if not fahrenheit and metric:
            return metric.get("default")
        return spec_for_key.get("default")

    action_id = None
    try:
        # VehicleManager's control methods (lock/unlock/start_climate/...)
        # each return Kia's own server-issued job id ("Xid") for the
        # request -- previously discarded here. check_action_status(vehicle_
        # id, action_id) can later poll whether it actually completed; that
        # polling isn't wired up yet (Kia USA's implementation of it is a
        # weak one-shot check, not worth building on without more research),
        # but surfacing the id now means it's at least available for a
        # caller/log line to reference, rather than lost the moment this
        # function returns.
        if call == "climate_options":
            try:
                from hyundai_kia_connect_api.ApiImpl import ClimateRequestOptions
            except Exception as exc:  # noqa: BLE001
                raise ClientError(
                    "this hyundai_kia_connect_api version has no ClimateRequestOptions"
                ) from exc
            co = ClimateRequestOptions()
            for key in opt_specs:
                val = _with_default(key)
                if val is not None and hasattr(co, key):
                    setattr(co, key, val)
            action_id = method(vehicle_id, co)
        elif call == "positional":
            args = [_with_default(a) for a in spec.get("args", [])]
            action_id = method(vehicle_id, *args)
        elif call == "poi":
            action_id = method(vehicle_id, [_build_poi(opts)])
        else:
            action_id = method(vehicle_id)
    except ClientError:
        raise
    except NotImplementedError as exc:
        raise ClientError(
            f"'{name}' isn't available for this region yet "
            "(waiting on a hyundai_kia_connect_api implementation)"
        ) from exc
    except Exception as exc:  # noqa: BLE001
        # A request timeout (the HTTP call itself, or "the server fails to
        # establish a connection with the car" -- see the library's own
        # ApiImplSession, which wraps requests.exceptions.Timeout into
        # exactly this) means we genuinely don't know whether the command
        # reached the vehicle -- Kia's protocol has no ID-less way to check
        # afterward. That's categorically different from a clear rejection
        # (bad PIN, unsupported command, etc.), so it needs its own
        # exception type rather than a flat "failed", so a caller can avoid
        # treating an immediate blind retry as obviously safe.
        try:
            from hyundai_kia_connect_api.exceptions import RequestTimeoutError
        except Exception:  # noqa: BLE001
            RequestTimeoutError = ()  # noqa: N806 -- library too old to have it
        if RequestTimeoutError and isinstance(exc, RequestTimeoutError):
            raise CommandUnconfirmed(
                f"'{name}' request timed out -- Kia's servers may or may not "
                "have received it; the vehicle's actual state is unknown "
                "until its next status refresh"
            ) from exc
        raise ClientError(f"{spec['method']} failed: {type(exc).__name__}: {exc}") from exc

    return {"ok": True, "command": name, "vehicleId": vehicle_id, "actionId": action_id}


def _geocode(address):
    """address string -> (lat, lon, display_name) via OpenStreetMap Nominatim."""
    import json as _json
    import urllib.parse
    import urllib.request

    url = "https://nominatim.openstreetmap.org/search?" + urllib.parse.urlencode(
        {"q": address, "format": "json", "limit": 1}
    )
    req = urllib.request.Request(url, headers={"User-Agent": "MMM-KiaAccess (kia_client)"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            rows = _json.load(resp)
    except Exception as exc:  # noqa: BLE001
        raise ClientError(f"geocoding failed for {address!r}: {exc}") from exc
    if not rows:
        raise ClientError(f"could not find a location for {address!r}")
    row = rows[0]
    return float(row["lat"]), float(row["lon"]), row.get("display_name") or address


def _build_poi(opts):
    """opts {name, address?, latitude?, longitude?} -> a POIInfo (geocoding the
    address when no explicit lat/lon is given)."""
    try:
        from hyundai_kia_connect_api.ApiImpl import POICoord, POIInfo
    except Exception as exc:  # noqa: BLE001
        raise ClientError(
            "this hyundai_kia_connect_api version has no POIInfo (send-to-car)"
        ) from exc

    lat = opts.get("latitude")
    lon = opts.get("longitude")
    addr = (opts.get("address") or "").strip()
    if lat is None or lon is None:
        if not addr:
            raise ClientError("send-to-car needs latitude + longitude, or an address")
        lat, lon, resolved = _geocode(addr)
        addr = addr or resolved
    return POIInfo(
        name=(opts.get("name") or "").strip() or addr or "Destination",
        addr=addr,
        coord=POICoord(lat=float(lat), lon=float(lon)),
    )
