# GENERATED by scripts/sync-core.js -- edit the root-level copy of this file instead, then run `npm run sync`.
"""Charge-session tracking - Python port of core/sessions.js.

Kept line-for-line with the JS; both are exercised in CI
(test/sessions.test.js / test/sessions_test.py).
"""
from __future__ import annotations

import re
import time

DEFAULT_CAPACITY_KWH = 99.8  # Kia EV9 usable
GAP_MIN = 45
MIN_KWH = 0.3

# See trips.py's mirror of this same helper for why: DEFAULT_CAPACITY_KWH is
# the EV9's own usable pack size and must never stand in as a generic
# "capacity unknown" guess for some other model, or that model's own
# energy/cost analytics would silently be computed off the wrong car's
# battery size.
# [\s-]* tolerates a space, hyphen, or nothing between "ev" and "9" (Kia's
# own API-reported model string isn't guaranteed to format it identically
# across regions/brands -- this is a best-effort heuristic, not a certainty;
# capacityKwh/capacity_kwh (checked first, in resolveCap()/_resolve_cap()
# below) is the reliable way to get a correct pack size for ANY vehicle,
# EV9 included, if this string match ever misses).
# (?!\d) -- a trailing digit means this is some OTHER model whose name
# merely starts with "ev9" (a hypothetical future "EV90"/"EV99"), not an
# EV9 trim/variant (real examples like "EV9 GT-Line" still match fine,
# since a space isn't a digit).
_EV9_RE = re.compile(r"ev[\s-]*9(?!\d)", re.IGNORECASE)


def _is_ev9(model) -> bool:
    return bool(model) and bool(_EV9_RE.search(str(model)))


def _resolve_cap(opts) -> float | None:
    cap = _num(opts.get("capacityKwh"))
    if cap is None and _is_ev9(opts.get("model")):
        cap = DEFAULT_CAPACITY_KWH
    return cap


def _num(v):
    if v is None or v == "":
        return None
    try:
        f = float(v)
    except (TypeError, ValueError):
        return None
    return f if f == f and f not in (float("inf"), float("-inf")) else None


def _round(n, dp=2):
    f = 10 ** dp
    return round(n * f) / f


def _tri(v):
    return v if v is True or v is False else None


def _rate_for(at_home, opts):
    """which per-kWh rate applies to a session, given where it charged"""
    home = _num(opts.get("pricePerKwh")) or 0
    away = _num(opts.get("awayPricePerKwh"))
    return away if (at_home is False and away is not None) else home


def update(open_s, cur, opts=None):
    """Fold one state sample into session tracking.

    open_s: dict | None   session in progress
    cur:    {"t", "charging", "plugged", "batteryPct", "chargeKw", "atHome"}
            atHome True/False/None(unknown) -> which rate the session is costed at
    opts:   {"pricePerKwh", "awayPricePerKwh", "capacityKwh", "minKwh", "gapMin"}
    -> {"open": dict|None, "closed": dict|None}
    """
    opts = opts or {}
    cap = _resolve_cap(opts)
    min_kwh = _num(opts.get("minKwh"))
    if min_kwh is None:
        min_kwh = MIN_KWH
    gap_ms = (_num(opts.get("gapMin")) or GAP_MIN) * 60000

    t = _num(cur.get("t")) or (time.time() * 1000)
    pct = _num(cur.get("batteryPct"))
    kw = _num(cur.get("chargeKw"))
    charging = cur.get("charging") is True
    # "not confirmed unplugged" (True OR unknown/None), not "confirmed
    # plugged" -- a genuinely unknown reading (a momentary API hiccup) must
    # not prematurely end a real session, but this is NOT "hold open
    # indefinitely": the gap_ms window below is measured from lastChargingAt,
    # so an unknown/plugged reading only keeps a session open for the same
    # bounded grace period (default 45 min, see GAP_MIN) that a real pause
    # already gets, never longer.
    plugged_not_confirmed_unplugged = cur.get("plugged") is not False

    if charging and not open_s:
        return {
            "open": {
                "startedAt": t, "lastChargingAt": t,
                "startPct": pct, "lastPct": pct, "peakKw": kw or 0,
                "atHome": _tri(cur.get("atHome")),
                "rate": _num(cur.get("rate")),
                "rateLabel": cur.get("rateLabel") or None,
                # activeMs: sum of the gaps between CONSECUTIVE charging=True
                # samples only -- see close()'s activeAvgKw comment below.
                # 0, not None: this first sample has no prior one to diff.
                "activeMs": 0, "lastSampleAt": t, "lastSampleCharging": True,
            },
            "closed": None,
        }
    if not open_s:
        return {"open": None, "closed": None}

    if charging:
        if open_s.get("lastSampleCharging") is True and open_s.get("lastSampleAt") is not None:
            open_s["activeMs"] = (open_s.get("activeMs") or 0) + (t - open_s["lastSampleAt"])
        open_s["lastSampleAt"] = t
        open_s["lastSampleCharging"] = True
        open_s["lastChargingAt"] = t
        if open_s.get("atHome") is None and _tri(cur.get("atHome")) is not None:
            open_s["atHome"] = cur.get("atHome")
        if open_s.get("rate") is None and _num(cur.get("rate")) is not None:
            open_s["rate"] = _num(cur.get("rate"))
            open_s["rateLabel"] = cur.get("rateLabel") or open_s.get("rateLabel")
        if pct is not None:
            open_s["lastPct"] = pct
            if open_s.get("startPct") is None:
                open_s["startPct"] = pct
        if kw is not None and kw > open_s["peakKw"]:
            open_s["peakKw"] = kw
        return {"open": open_s, "closed": None}

    if (plugged_not_confirmed_unplugged
            and t - (open_s.get("lastChargingAt") or open_s["startedAt"]) < gap_ms):
        open_s["lastSampleAt"] = t
        open_s["lastSampleCharging"] = False
        if pct is not None:
            open_s["lastPct"] = pct
        return {"open": open_s, "closed": None}

    end_pct = pct if pct is not None else open_s.get("lastPct")
    start_pct = open_s.get("startPct")
    gained = max(0, end_pct - start_pct) if (start_pct is not None and end_pct is not None) else None
    kwh = (gained / 100) * cap if (gained is not None and cap is not None) else None
    mins = max(0, round((open_s.get("lastChargingAt", t) - open_s["startedAt"]) / 60000))
    active_mins = max(0, round((open_s.get("activeMs") or 0) / 60000))
    rate = open_s["rate"] if open_s.get("rate") is not None else _rate_for(open_s.get("atHome"), opts)
    # atHome True/False -> a confirmed bucket; atHome left None (no home
    # zone configured, or no GPS fix ever came in this session) is
    # genuinely UNKNOWN, not "assume home" -- _rate_for() above still
    # prices it at the home rate (the best guess available for cost
    # purposes), but the bucket a session is filed under for home/away
    # analytics must not silently claim a confirmed location we never had.
    at_home = open_s.get("atHome")
    where = open_s.get("rateLabel") or (
        "home" if at_home is True else "away" if at_home is False else "unknown"
    )
    s = {
        "startedAt": open_s["startedAt"],
        "endedAt": open_s.get("lastChargingAt") or t,
        "minutes": mins,
        # minutes actually spent mid-charge (consecutive charging=True
        # samples only) -- excludes scheduled-charging pauses / tapering
        # gaps that `minutes` above folds into the same session. Always
        # <= minutes; the gap between the two IS the plugged-in-but-not-
        # drawing time.
        "activeMinutes": active_mins,
        "startPct": start_pct,
        "endPct": end_pct,
        "gainedPct": _round(gained, 1) if gained is not None else None,
        "kwh": _round(kwh, 2) if kwh is not None else None,
        "cost": _round(kwh * rate, 2) if (kwh is not None and rate > 0) else None,
        "peakKw": _round(open_s["peakKw"], 1),
        # kWh delivered over the WHOLE session span, pauses included -- "if
        # I leave it plugged in for a session shaped like this, what rate
        # should I plan around". Kept for backwards compatibility; this is
        # what the analytics/SoC-band aggregates already read.
        "avgKw": _round(kwh / (mins / 60), 1) if (kwh is not None and mins > 0) else None,
        # kWh delivered over only the time actually spent charging -- the
        # charger's real rate. Differs from avgKw whenever a session had a
        # scheduled-charging pause or a long standby/taper.
        "activeAvgKw": _round(kwh / (active_mins / 60), 1) if (kwh is not None and active_mins > 0) else None,
        "pricePerKwh": rate or None,
        "location": where,
        "costSource": "rate" if (kwh is not None and rate > 0) else None,
    }
    closed = s if (s["kwh"] is not None and s["kwh"] >= min_kwh) else None
    return {"open": None, "closed": closed}


def apply_cost(session, cost, source="external"):
    """Replace a session's cost with a known figure (public-charging integration
    or a hand-entered value); keeps the rate estimate as `estimatedCost`."""
    if not session:
        return session
    out = dict(session)
    c = _num(cost)
    if c is None or c < 0:
        return out
    if out.get("estimatedCost") is None:
        out["estimatedCost"] = out.get("cost")
    out["cost"] = _round(c, 2)
    out["costSource"] = source or "external"
    return out


def progress(open_s, cur, opts=None):
    """Live figures for the session in progress. None if no session."""
    if not open_s:
        return None
    opts = opts or {}
    cap = _resolve_cap(opts)
    price = open_s["rate"] if open_s.get("rate") is not None else _rate_for(open_s.get("atHome"), opts)
    t = _num(cur.get("t")) or (time.time() * 1000)
    pct = _num(cur.get("batteryPct"))
    last_pct = pct if pct is not None else open_s.get("lastPct")
    start_pct = open_s.get("startPct")
    kwh_soc = (
        max(0, (last_pct - start_pct) / 100 * cap)
        if (start_pct is not None and last_pct is not None and cap is not None) else 0
    )
    kw = _num(cur.get("chargeKw"))
    if kw is None:
        kw = open_s.get("peakKw") or 0
    drift_ms = max(0, min(15 * 60000, t - (open_s.get("lastChargingAt") or open_s["startedAt"])))
    kwh = kwh_soc + (kw * (drift_ms / 3600000) if cur.get("charging") is True else 0)
    return {
        "kwh": _round(kwh, 2),
        "cost": _round(kwh * price, 2) if price > 0 else None,
        "gainedPct": (
            _round(last_pct - start_pct, 1)
            if (start_pct is not None and last_pct is not None) else None
        ),
        "minutes": max(0, round((t - open_s["startedAt"]) / 60000)),
    }


def summary(sessions, days=30):
    """totals over the last `days`, split home / away"""
    cutoff = (time.time() * 1000) - days * 864e5
    acc = {k: {"count": 0, "kwh": 0.0, "cost": 0.0, "have": False}
           for k in ("all", "home", "away", "unknown")}
    for s in sessions or []:
        if not s or _num(s.get("endedAt")) is None or s["endedAt"] < cutoff:
            continue
        # "home" (or a session from before location tracking existed at
        # all, which has no `location` field whatsoever) -> home bucket;
        # the explicit "unknown" value (see update() above) means this
        # specific session's location genuinely couldn't be determined and
        # must NOT be folded into either home or away; anything else --
        # "away" or a named public-charger zone -- is the away bucket.
        loc = s.get("location")
        where = "unknown" if loc == "unknown" else ("home" if loc in (None, "home") else "away")
        for a in (acc["all"], acc[where]):
            a["count"] += 1
            if s.get("kwh") is not None:
                a["kwh"] += s["kwh"]
            if s.get("cost") is not None:
                a["cost"] += s["cost"]
                a["have"] = True

    def out(a):
        return {"count": a["count"], "kwh": _round(a["kwh"], 1),
                "cost": _round(a["cost"], 2) if a["have"] else None}

    r = out(acc["all"])
    r["home"] = out(acc["home"])
    r["away"] = out(acc["away"])
    r["unknown"] = out(acc["unknown"])
    return r
