# GENERATED by scripts/sync-core.js -- edit the root-level copy of this file instead, then run `npm run sync`.
"""Python port of core/state.js buildState().

Turns a flat map of `vehicle.*` values into the normalised dict consumed by
conditions.evaluate(). Kept line-for-line with the JS; the fixtures/ corpus is
run through both in CI.
"""
from __future__ import annotations

import time

_TRUE = {True, "true", "True", 1, "1"}
_FALSE = {False, "false", "False", 0, "0"}


def powertrain_for(engine_type) -> str:
    """Raw vehicle.engine_type -> "ev"|"gas"|"hybrid". Unset/unrecognised
    defaults to "ev" -- see core/state.js's identical comment. Exposed as
    its own function (not just inline in build_state()) so button.py/
    number.py can gate EV-only commands/entities from coordinator.vehicle
    directly, without needing a full build_state() flat-map round trip."""
    t = str(engine_type or "").upper()
    if t == "ICE":
        return "gas"
    if t in ("PHEV", "HEV"):
        return "hybrid"
    return "ev"


def can_plug_in_for(engine_type) -> bool:
    """Raw vehicle.engine_type -> can this vehicle be plugged in at all?
    False for ICE (gas) AND HEV (a conventional, non-plug hybrid -- e.g. a
    Kia Sportage Hybrid or Hyundai Tucson Hybrid, sold alongside a PHEV
    version of the same car) -- powertrain_for() maps both PHEV and HEV to
    the same "hybrid" bucket, which isn't fine enough for anything that
    means "has a plug" (the notPluggedInHome alert, charging buttons/
    charge-limit sliders). Unset/unrecognised defaults to True, same
    fail-safe reasoning as powertrain_for()."""
    t = str(engine_type or "").upper()
    return t not in ("ICE", "HEV")


def _bool(f, key):
    v = f.get("vehicle." + key)
    if v in _TRUE:
        return True
    if v in _FALSE:
        return False
    # some binary_sensor-shaped fields aren't strict 0/1 -- e.g. the EV9's
    # ev_battery_is_plugged_in comes back as a connector-type code (seen: 4
    # while actively charging), not a boolean. Any other finite number: 0
    # is false, anything else is true. Strings that aren't "true"/"false"
    # stay unknown (None) rather than guessing.
    if isinstance(v, (int, float)) and not isinstance(v, bool) and v == v and v not in (
        float("inf"), float("-inf")
    ):
        return v != 0
    return None


def _num(f, key):
    raw = f.get("vehicle." + key)
    if raw is None or raw == "":
        return None
    try:
        v = float(raw)
    except (TypeError, ValueError):
        return None
    return v if v == v and v not in (float("inf"), float("-inf")) else None


def _any_true(f, *keys):
    vals = [_bool(f, k) for k in keys]
    if any(v is True for v in vals):
        return True
    if all(v is False for v in vals):
        return False
    return None


def build_state(flat, opts=None):
    f = flat or {}
    opts = opts or {}

    hs = f.get("vehicle.headlamp_status")
    headlights = _any_true(f, "headlamp_left_low", "headlamp_right_low",
                           "headlamp_left_high", "headlamp_right_high",
                           "headlamp_left_bifunc", "headlamp_right_bifunc")
    _HEADLIGHT_ON = ("on", "low", "high", "bifunc", "1", "true")
    _HEADLIGHT_OFF = ("off", "none", "0", "false")
    if headlights is None and isinstance(hs, str):
        t = hs.strip().lower()
        # allow-list, not a deny-list: an unrecognized string ("unknown",
        # "unavailable", "error", "not_available", ...) must stay unknown
        # (None), not silently read as "on".
        if t in _HEADLIGHT_ON:
            headlights = True
        elif t in _HEADLIGHT_OFF:
            headlights = False
        else:
            headlights = None

    air_temp_c = _num(f, "air_temperature")        # climate set-point
    outside_temp_c = _num(f, "outside_temperature")

    def climate():
        if _bool(f, "air_control_is_on") is not True:
            return None
        if air_temp_c is not None and outside_temp_c is not None:
            if air_temp_c - outside_temp_c >= 1:
                return "heat"
            if outside_temp_c - air_temp_c >= 1:
                return "cool"
        return "on"

    def charge_limit():
        ac = _num(f, "ev_charge_limits_ac")
        dc = _num(f, "ev_charge_limits_dc")
        vals = [v for v in (ac, dc) if v is not None and v > 0]
        return max(vals) if vals else None

    def token_age_days():
        ts = f.get("_meta.tokenEnrolledAt")
        if not ts:
            return None
        try:
            import datetime
            dt = datetime.datetime.fromisoformat(str(ts).replace("Z", "+00:00"))
            ms = time.time() * 1000 - dt.timestamp() * 1000
        except Exception:
            return None
        return ms / 864e5 if ms >= 0 else None

    # genuine fault lamps the car reports (only those that exist AND are on)
    _FAULTS = [
        ("brake_oil_warning_is_on", "Brake fluid low"),
        ("brake_fluid_warning_is_on", "Brake fluid low"),
        ("breaking_oil_warning_is_on", "Brake fluid low"),
        ("battery_auxiliary_fail_warning_is_on", "12V battery system fault"),
        ("air_bag_warning_is_on", "Airbag warning"),
        ("srs_warning_is_on", "Airbag (SRS) warning"),
        ("abs_warning_is_on", "ABS fault"),
        ("esc_warning_is_on", "Stability control fault"),
        ("engine_oil_warning_is_on", "Engine oil warning"),
        ("break_pad_warning_is_on", "Brake pad wear"),
        ("brake_pad_warning_is_on", "Brake pad wear"),
    ]
    faults = []
    for key, label in _FAULTS:
        if _bool(f, key) is True and label not in faults:
            faults.append(label)

    powertrain = powertrain_for(f.get("vehicle.engine_type"))
    can_plug_in = can_plug_in_for(f.get("vehicle.engine_type"))

    # ev_driving_range is EV-only -- see core/state.js's identical comment.
    range_km = _num(f, "ev_driving_range")
    if range_km is None or range_km <= 0:
        range_km = _num(f, "total_driving_range")

    return {
        "batteryPct": _num(f, "ev_battery_percentage"),
        "rangeKm": range_km,
        "chargeKw": _num(f, "ev_charging_power"),
        "chargeAmps": _num(f, "ev_charging_current"),
        "charging": _bool(f, "ev_battery_is_charging"),
        "plugged": _bool(f, "ev_battery_is_plugged_in"),
        "v2l": _bool(f, "ev_v2l_status"),
        "v2x": _bool(f, "ev_v2x_status"),
        "locked": _bool(f, "is_locked"),
        "carOn": _any_true(f, "engine_is_running", "accessory_on", "ign3", "remote_ignition"),
        "headlights": headlights,
        "doorFL": _bool(f, "front_left_door_is_open"),
        "doorFR": _bool(f, "front_right_door_is_open"),
        "doorRL": _bool(f, "back_left_door_is_open"),
        "doorRR": _bool(f, "back_right_door_is_open"),
        "winFL": _bool(f, "front_left_window_is_open"),
        "winFR": _bool(f, "front_right_window_is_open"),
        "winRL": _bool(f, "back_left_window_is_open"),
        "winRR": _bool(f, "back_right_window_is_open"),
        "hood": _bool(f, "hood_is_open"),
        "trunk": _bool(f, "trunk_is_open"),
        "sunroof": _bool(f, "sunroof_is_open"),
        "defrost": _bool(f, "defrost_is_on"),
        "rearHeat": _bool(f, "back_window_heater_is_on"),
        "mirrorHeat": _bool(f, "side_mirror_heater_is_on"),
        "steerHeat": _bool(f, "steering_wheel_heater_is_on"),
        "climate": climate(),
        "airTempC": air_temp_c,
        "outsideTempC": outside_temp_c,
        "tyreAny": _bool(f, "tire_pressure_all_warning_is_on"),
        "tyreFL": _bool(f, "tire_pressure_front_left_warning_is_on"),
        "tyreFR": _bool(f, "tire_pressure_front_right_warning_is_on"),
        "tyreRL": _bool(f, "tire_pressure_rear_left_warning_is_on"),
        "tyreRR": _bool(f, "tire_pressure_rear_right_warning_is_on"),
        "car12vPct": _num(f, "car_battery_percentage"),
        "chargeLimitPct": charge_limit(),
        "capacityKwh": _num(f, "ev_battery_capacity"),
        "serviceKm": _num(f, "next_service_distance"),
        "odometerKm": _num(f, "odometer"),
        "locationLat": _num(f, "location_latitude"),
        "locationLon": _num(f, "location_longitude"),
        "faults": faults,
        "powertrain": powertrain,
        "canPlugIn": can_plug_in,
        "fuelPct": _num(f, "fuel_level"),
        "history": opts.get("history") or [],
        "units": opts.get("units") or "imperial",
        "tokenAgeDays": token_age_days(),
        "otpLifetimeDays": opts.get("otpLifetimeDays"),
        "otpWarnDays": opts.get("otpWarnDays"),
    }
