/* Sync the shared specs + client into the Home Assistant integration.
 *
 *   node scripts/sync-core.js            # write
 *   node scripts/sync-core.js --check    # fail if anything would change (CI)
 *
 * The HA custom component must be self-contained (HACS installs only that
 * folder), so core/entities.json, core/commands.json and kia_client.py are
 * copied in, and custom_components/kia_access/services.yaml is generated from
 * commands.json. This is the "define a feature once" guarantee.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const HA = path.join(ROOT, "custom_components", "kia_access");
const check = process.argv.includes("--check");

const outputs = {};

// 1:1 copies
for (const rel of [
  "core/entities.json",
  "core/commands.json",
  "kia_client.py",
  "conditions.py",
  "vehicle_state.py",
  "sessions.py",
  "range.py",
  "routing.py",
  "trips.py"
]) {
  outputs[path.join(HA, path.basename(rel))] = fs.readFileSync(path.join(ROOT, rel), "utf8");
}

// bundled Lovelace card: catalogues + shared core modules + card class
const read = (rel) => fs.readFileSync(path.join(ROOT, rel), "utf8");
outputs[path.join(HA, "frontend", "kia-access-card.js")] = [
  "/* GENERATED by scripts/sync-core.js - edit card/kia-access-card.src.js or core/*. */",
  "(function(){var g=(typeof self!=='undefined')?self:window;",
  "g.KiaAccessEntities=" + read("core/entities.json").trim() + ";",
  "g.KiaAccessCommands=" + read("core/commands.json").trim() + ";})();",
  read("core/state.js"),
  read("core/visuals.js"),
  read("core/conditions.js"),
  read("core/range.js"),
  read("core/isoline.js"),
  read("core/trips.js"),
  read("card/kia-access-card.src.js"),
  read("card/kia-range-map-card.src.js")
].join("\n");

// generated services.yaml
const commands = JSON.parse(fs.readFileSync(path.join(ROOT, "core/commands.json"), "utf8")).commands;
const TYPE_SELECTOR = {
  int: (o) => ({ number: { min: o.min, max: o.max, mode: "box", unit_of_measurement: o.unit } }),
  float: (o) => ({ number: { min: o.min, max: o.max, step: o.step || 0.5, mode: "box", unit_of_measurement: o.unit } }),
  bool: () => ({ boolean: {} }),
  string: () => ({ text: {} })
};
let yaml =
  "# GENERATED by scripts/sync-core.js from core/commands.json — do not edit.\n";
for (const c of commands) {
  yaml += `\n${c.key}:\n`;
  yaml += `  name: ${JSON.stringify(c.name)}\n`;
  yaml += `  description: ${JSON.stringify(
    c.name + " — Kia Access" +
      (c.dormant ? " (not available in all regions yet — returns an error until it is)" : "")
  )}\n`;
  yaml += "  fields:\n";
  yaml += "    entry_id:\n";
  yaml += "      name: Account\n";
  yaml += "      description: Config entry id (only needed with multiple accounts).\n";
  yaml += "      required: false\n";
  yaml += "      selector:\n        config_entry:\n          integration: kia_access\n";
  for (const [name, o] of Object.entries(c.options || {})) {
    const sel = (TYPE_SELECTOR[o.type] || TYPE_SELECTOR.string)(o);
    yaml += `    ${name}:\n`;
    yaml += `      name: ${JSON.stringify(name.replace(/_/g, " ").replace(/^./, (m) => m.toUpperCase()))}\n`;
    yaml += `      required: false\n`;
    if (o.default !== undefined) yaml += `      default: ${JSON.stringify(o.default)}\n`;
    yaml += `      selector:\n`;
    yaml += indentSelector(sel, "        ");
  }
}
// hand-written, non-command services (registered in __init__.py)
yaml +=
  "\nrefresh_calendar_destinations:\n" +
  '  name: "Refresh calendar destinations"\n' +
  '  description: "Re-read the configured calendars now and geocode any new event locations for the reachable-destinations list / range map."\n' +
  "  fields:\n" +
  "    entry_id:\n" +
  "      name: Account\n" +
  "      description: Config entry id (only needed with multiple accounts).\n" +
  "      required: false\n" +
  "      selector:\n        config_entry:\n          integration: kia_access\n";
yaml +=
  "\nset_charge_cost:\n" +
  '  name: "Set charge cost"\n' +
  '  description: "Override the logged cost of a charge session with a known figure (a public-charging receipt)."\n' +
  "  fields:\n" +
  "    cost:\n" +
  "      name: Cost\n" +
  "      description: The actual amount paid.\n" +
  "      required: true\n" +
  "      selector:\n        number:\n          min: 0\n          max: 1000\n          step: 0.01\n          mode: box\n" +
  "    started_at:\n" +
  "      name: Session start (ms)\n" +
  '      description: "startedAt of the session to change (from sensor.<v>_last_charge attributes). Omit for the most recent session."\n' +
  "      required: false\n" +
  "      selector:\n        number:\n          mode: box\n" +
  "    entry_id:\n" +
  "      name: Account\n" +
  "      description: Config entry id (only needed with multiple accounts).\n" +
  "      required: false\n" +
  "      selector:\n        config_entry:\n          integration: kia_access\n";
yaml +=
  "\ntest_alert:\n" +
  '  name: "Send a test alert"\n' +
  '  description: "Fires a fake kia_access_alert event -- no real condition needed. Use it to check a notify target, the alert_to_phone blueprint, quiet hours, or the Lock / Start-charge action buttons (pick unlocked / not_plugged_home / charge_interrupted for those)."\n' +
  "  fields:\n" +
  "    reason:\n" +
  "      name: Reason\n" +
  "      description: Which condition to pretend fired.\n" +
  "      required: false\n" +
  "      default: unlocked\n" +
  "      selector:\n        select:\n          custom_value: true\n          options:\n" +
  "            - unlocked\n            - door_open\n            - window_open\n" +
  "            - not_plugged_home\n            - charge_interrupted\n" +
  "            - tyre_pressure\n            - battery_12v_critical\n" +
  "            - unexpected_move\n            - cant_get_home\n" +
  "            - vehicle_fault\n" +
  "    level:\n" +
  "      name: Level\n" +
  "      required: false\n" +
  "      default: warning\n" +
  "      selector:\n        select:\n          options:\n            - info\n            - warning\n            - critical\n" +
  "    active:\n" +
  "      name: Active\n" +
  '      description: "On = the alert just fired. Off = it just cleared (sends clear_notification instead)."\n' +
  "      required: false\n" +
  "      default: true\n" +
  "      selector:\n        boolean: {}\n" +
  "    entry_id:\n" +
  "      name: Account\n" +
  "      description: Config entry id (only needed with multiple accounts).\n" +
  "      required: false\n" +
  "      selector:\n        config_entry:\n          integration: kia_access\n";
outputs[path.join(HA, "services.yaml")] = yaml;

function indentSelector(obj, pad) {
  let s = "";
  for (const [k, v] of Object.entries(obj)) {
    if (v && typeof v === "object" && Object.keys(v).length) {
      s += `${pad}${k}:\n` + indentSelector(v, pad + "  ");
    } else if (v && typeof v === "object") {
      s += `${pad}${k}: {}\n`;
    } else if (v === undefined) {
      /* skip */
    } else {
      s += `${pad}${k}: ${JSON.stringify(v)}\n`;
    }
  }
  return s;
}

let stale = false;
for (const [file, content] of Object.entries(outputs)) {
  const cur = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (cur === content) continue;
  stale = true;
  if (check) {
    console.error("stale: " + path.relative(ROOT, file));
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log("wrote " + path.relative(ROOT, file));
  }
}

if (check && stale) {
  console.error("\nRun: node scripts/sync-core.js");
  process.exit(1);
}
if (!stale) console.log("custom_components/kia_access is in sync");
