/* Sync the shared specs + client into the Home Assistant integration.
 *
 *   node scripts/sync-core.js            # write
 *   node scripts/sync-core.js --check    # fail if anything would change (CI)
 *
 * The HA custom component must be self-contained (HACS installs only that
 * folder), so core/entities.json, core/commands.json and kia_client.py are
 * copied in, and custom_components/kia_access/services.yaml is generated from
 * commands.json. This is the "define a feature once" guarantee.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const HA = path.join(ROOT, "custom_components", "kia_access");
const check = process.argv.includes("--check");

const outputs = {};

// 1:1 copies
for (const rel of ["core/entities.json", "core/commands.json", "kia_client.py"]) {
  outputs[path.join(HA, path.basename(rel))] = fs.readFileSync(path.join(ROOT, rel), "utf8");
}

// generated services.yaml
const commands = JSON.parse(fs.readFileSync(path.join(ROOT, "core/commands.json"), "utf8")).commands;
const TYPE_SELECTOR = {
  int: (o) => ({ number: { min: o.min, max: o.max, mode: "box", unit_of_measurement: o.unit } }),
  float: (o) => ({ number: { min: o.min, max: o.max, step: 0.5, mode: "box", unit_of_measurement: o.unit } }),
  bool: () => ({ boolean: {} }),
  string: () => ({ text: {} })
};
let yaml =
  "# GENERATED by scripts/sync-core.js from core/commands.json — do not edit.\n";
for (const c of commands) {
  yaml += `\n${c.key}:\n`;
  yaml += `  name: ${JSON.stringify(c.name)}\n`;
  yaml += `  description: ${JSON.stringify((c.name) + " — Kia Access")}\n`;
  yaml += "  fields:\n";
  yaml += "    entry_id:\n";
  yaml += "      name: Account\n";
  yaml += "      description: Config entry id (only needed with multiple accounts).\n";
  yaml += "      required: false\n";
  yaml += "      selector:\n        config_entry:\n          integration: kia_access\n";
  for (const [name, o] of Object.entries(c.options || {})) {
    const sel = (TYPE_SELECTOR[o.type] || TYPE_SELECTOR.string)(o);
    yaml += `    ${name}:\n`;
    yaml += `      name: ${JSON.stringify(name.replace(/_/g, " ").replace(/^./, (m) => m.toUpperCase()))}\n`;
    yaml += `      required: false\n`;
    if (o.default !== undefined) yaml += `      default: ${JSON.stringify(o.default)}\n`;
    yaml += `      selector:\n`;
    yaml += indentSelector(sel, "        ");
  }
}
outputs[path.join(HA, "services.yaml")] = yaml;

function indentSelector(obj, pad) {
  let s = "";
  for (const [k, v] of Object.entries(obj)) {
    if (v && typeof v === "object" && Object.keys(v).length) {
      s += `${pad}${k}:\n` + indentSelector(v, pad + "  ");
    } else if (v && typeof v === "object") {
      s += `${pad}${k}: {}\n`;
    } else if (v === undefined) {
      /* skip */
    } else {
      s += `${pad}${k}: ${JSON.stringify(v)}\n`;
    }
  }
  return s;
}

let stale = false;
for (const [file, content] of Object.entries(outputs)) {
  const cur = fs.existsSync(file) ? fs.readFileSync(file, "utf8") : null;
  if (cur === content) continue;
  stale = true;
  if (check) {
    console.error("stale: " + path.relative(ROOT, file));
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log("wrote " + path.relative(ROOT, file));
  }
}

if (check && stale) {
  console.error("\nRun: node scripts/sync-core.js");
  process.exit(1);
}
if (!stale) console.log("custom_components/kia_access is in sync");
